# lsi: false
# safe: true
# source: [your repo's top level directory]
# incremental: false
# highlighter: rouge
# gist:
#   noscript: false
# kramdown:
#  math_engine: mathjax
# domain: pubkeyspace.github.io
# url: https://pubkeyspace.github.io/empanadas/
# baseurl: /
markdown: kramdown

plugins:
# default github-pages plugins
- jekyll-coffeescript
- jekyll-commonmark-ghpages
- jekyll-default-layout
- jekyll-gist
- jekyll-github-metadata
- jekyll-optional-front-matter
- jekyll-paginate
- jekyll-readme-index
- jekyll-relative-links
- jekyll-titles-from-headings

# maybe?
- jekyll-include-cache
- jekyll-octicons
